name: Build

on:
  push:
    branches:
      - master

jobs:
  snapshot-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java environment
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: $SETTINGS_PATH # location for the settings.xml file
      - name: Get the project version
        run: |
          echo "::set-env name=PROJECT_VERSION::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
      - name: Current project version
        run: echo "$PROJECT_VERSION"
      - name: Publish snapshot release
        if: endsWith(env.PROJECT_VERSION, 'SNAPSHOT')
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SETTINGS_PATH: ${{ github.workspace }}/.github/workflows/settings.xml
        run: mvn -B -s $SETTINGS_PATH deploy
